// Generated from the web app texts (src/i18n.tsx) plus app-only texts (ci/strings_extra.json).
// Edit there and run ci/gen_strings.py, or edit here directly.

const Map<String, Map<String, String>> strings = {
  'de': {
    'add.cover': 'Cover fotografieren',
    'add.coverText': 'Vorderseite fotografieren – das Foto wird das Cover, Titel wird erkannt (mit API-Schlüssel) oder eingetippt.',
    'add.import': 'Datei importieren',
    'add.importText': 'JSON-Datei aus einer Sicherung oder aus einer Claude-Sitzung (Regalfotos).',
    'add.manual': 'Von Hand eintragen',
    'add.manualText': 'Für Spiele, DVDs, alte oder chinesische Ausgaben ohne Barcode.',
    'add.scan': 'Barcode scannen',
    'add.scanText': 'ISBN oder EAN mit der Kamera – Cover und Daten kommen aus dem Internet. Auch für „Habe ich das schon?“ im Buchladen.',
    'add.search': 'Online suchen',
    'add.searchText': 'Nach Titel und Autor:in in Google Books, Open Library und MusicBrainz suchen.',
    'add.shelf': 'Regalfoto erkennen',
    'add.shelfText': 'Ganzes Regal fotografieren, Claude liest die Buchrücken, du prüfst die Liste.',
    'add.shelfTextNoKey': 'Braucht einen Claude-API-Schlüssel (Optionen).',
    'add.tip': 'Tipp: Der Raum, den du beim Hinzufügen wählst, wird für den nächsten Eintrag gemerkt.',
    'ai.addN': '{n} übernehmen',
    'ai.added': '{n} Einträge hinzugefügt. Unsichere sind unter „Zu prüfen“ markiert.',
    'ai.all': 'Alle auswählen',
    'ai.camera': 'Kamera',
    'ai.conf.low': 'geraten',
    'ai.conf.medium': 'unsicher',
    'ai.coverHint': 'Das Foto wird als Cover gespeichert; Titel und Daten werden erkannt und online ergänzt.',
    'ai.coverNoKey': 'Das Foto wird als Cover gespeichert; Titel tippst du ein (oder suchst ihn online).',
    'ai.dup': 'schon da',
    'ai.enrich': 'Cover & Details online ergänzen (Bücher, CDs)',
    'ai.enriching': 'Suche Details online …',
    'ai.enrichingN': 'Ergänze online {i} / {n} …',
    'ai.err.auth': 'Der API-Schlüssel wurde abgelehnt. Bitte unter Optionen prüfen.',
    'ai.err.network': 'Keine Verbindung zu Claude.',
    'ai.err.other': 'Fehler bei Claude',
    'ai.err.parse': 'Antwort nicht lesbar',
    'ai.err.rate': 'Zu viele Anfragen – kurz warten und nochmal versuchen.',
    'ai.err.refusal': 'Claude hat dieses Foto abgelehnt.',
    'ai.found': '{n} erkannt',
    'ai.gallery': 'Galerie',
    'ai.hintPh': 'Hinweis (optional), z. B. „chinesische Klassiker“',
    'ai.noKey': 'Für die Regalfoto-Erkennung brauchst du einen eigenen Claude-API-Schlüssel (unter Optionen). Alternativ: Fotos an Claude im Chat schicken und die erzeugte Datei importieren.',
    'ai.none': 'Keine auswählen',
    'ai.reading': 'Claude liest Foto {i} von {n} … (dauert ca. 30–90 s)',
    'ai.readingCover': 'Claude liest das Cover …',
    'ai.shelfHint': 'Möglichst gerade und nah fotografieren, ein Regalfach pro Foto. Mehrere Fotos aus der Galerie gehen auch.',
    'ai.take': 'Übernehmen',
    'any': 'Alle',
    'app.loading': 'Lädt …',
    'bulk.badKey': 'Google hat den API-Schlüssel abgelehnt. Bitte unter Optionen prüfen (Books API aktiviert?).',
    'bulk.count': '{n} Bücher mit fehlenden Infos.',
    'bulk.done': 'Fertig: {found} ergänzt, {missed} nicht gefunden.',
    'bulk.field.cover': 'Cover',
    'bulk.field.description': 'Klappentext',
    'bulk.field.isbn': 'ISBN',
    'bulk.field.publisher': 'Verlag',
    'bulk.field.year': 'Jahr',
    'bulk.found': 'Ergänzt ({n})',
    'bulk.intro': 'Geht alle Bücher durch, denen Cover, Verlag, Jahr, ISBN oder Klappentext fehlen, und sucht sie in Google Books (und Open Library) – per ISBN, sonst nach Titel und Autor:in. Übernommen wird nur, was eindeutig passt, und nur in leere Felder; deine Angaben werden nie überschrieben.',
    'bulk.missed': 'Nicht gefunden ({n})',
    'bulk.missedHint': 'Antippen und dort „Online ergänzen“ mit anderer Schreibweise versuchen – oder Cover fotografieren.',
    'bulk.noKey': 'Ohne eigenen Google-Books-Schlüssel ist das gemeinsame Tageslimit oft schnell erreicht. Mit Schlüssel (kostenlos, 1 000 Abfragen pro Tag) läuft es zuverlässig.',
    'bulk.nothing': 'Alle Bücher sind vollständig – oder wurden schon gesucht.',
    'bulk.quota': 'Google-Books-Tageslimit erreicht. Morgen weitermachen oder einen eigenen Schlüssel eintragen – die restlichen Bücher bleiben für den nächsten Lauf vorgemerkt.',
    'bulk.retry': 'Auch die {n} schon gesuchten nochmal versuchen',
    'bulk.short': 'Cover, Verlag, Jahr, ISBN und Klappentext für alle Bücher auf einmal aus Google Books holen.',
    'bulk.start': '{n} Bücher ergänzen',
    'bulk.stop': 'Anhalten',
    'bulk.stopped': 'Angehalten. Beim nächsten Start geht es mit den restlichen weiter.',
    'bulk.title': 'Fehlende Infos ergänzen',
    'bulkEdit.addTag': 'Schlagwort hinzufügen',
    'bulkEdit.apply': 'Auf {n} anwenden',
    'bulkEdit.checked': '„Zu prüfen“-Markierung entfernen',
    'bulkEdit.deleteConfirm': 'Wirklich {n} Einträge löschen?',
    'bulkEdit.intro': 'Nur was du hier änderst, wird bei allen ausgewählten Einträgen gesetzt – der Rest bleibt, wie er ist.',
    'bulkEdit.newRoom': 'Neuer Raum …',
    'bulkEdit.no': 'Nein',
    'bulkEdit.noRating': 'Keine Bewertung',
    'bulkEdit.noStatus': 'Kein Status',
    'bulkEdit.owned': 'Besitze ich',
    'bulkEdit.removeTag': 'Schlagwort entfernen',
    'bulkEdit.title': '{n} Einträge bearbeiten',
    'bulkEdit.unchanged': '– unverändert –',
    'bulkEdit.yes': 'Ja',
    'cat.add': 'Kategorie hinzufügen',
    'cat.mergeConfirm': '„{to}“ gibt es schon. Alles aus „{from}“ dorthin verschieben?',
    'cat.new': 'Name der neuen Kategorie:',
    'cat.none': '– ohne Kategorie –',
    'cat.own': 'Eigene',
    'cat.removeConfirm': 'Kategorie „{name}“ entfernen? {n} Einträge verlieren sie.',
    'cat.rename': 'Neuer Name für „{name}“:',
    'cat.reset': 'Standardliste wiederherstellen',
    'cat.resetConfirm': 'Liste wieder auf die Standard-Kategorien setzen? Kategorien, die Einträge schon haben, bleiben erhalten.',
    'close': 'Schließen',
    'cover.camera': 'Foto aufnehmen',
    'cover.change': 'Cover ändern',
    'cover.gallery': 'Aus Galerie',
    'cover.useOnline': 'Eigenes Foto entfernen (Online-Cover zeigen)',
    'creator.book': 'Autor:in',
    'creator.cd': 'Künstler:in',
    'creator.dvd': 'Regie',
    'creator.game': 'Autor:in / Verlag',
    'data.exportCsv': 'Als Tabelle exportieren (CSV)',
    'data.exportCsvShare': 'Tabelle teilen (CSV)',
    'data.exportJson': 'Sicherung exportieren (JSON)',
    'data.exportJsonShare': 'Sicherung teilen (z. B. in Google Drive)',
    'data.import': 'Sicherung / Datei importieren',
    'data.importError': 'Import fehlgeschlagen: {e}',
    'data.imported': 'Import: {added} neu, {updated} aktualisiert, {skipped} übersprungen (schon vorhanden).',
    'data.saved': 'Gespeichert.',
    'data.wipe': 'Alles löschen',
    'data.wipeConfirm': 'Wirklich alle {n} Einträge löschen? Vorher eine Sicherung exportieren!',
    'data.wipeType': 'Zum Bestätigen OK eintippen:',
    'detail.checked': 'Stimmt so',
    'detail.close': 'Schließen',
    'detail.delete': 'Löschen',
    'detail.deleteConfirm': '„{title}“ wirklich löschen?',
    'detail.edit': 'Bearbeiten',
    'detail.enrich': 'Online ergänzen',
    'detail.lend': 'Verleihen …',
    'detail.lendWho': 'An wen?',
    'detail.lentTo': 'Verliehen an {name} seit {date}',
    'detail.loan': 'Verleihen',
    'detail.loanPast': '{name}: {from} – {to}',
    'detail.needsCheck': 'Automatisch erkannt – bitte Titel und Autor:in prüfen.',
    'detail.notesPh': 'Was hat dir gefallen? Für wen ist es was?',
    'detail.place': 'Standort',
    'detail.recommend': 'Empfehlung',
    'detail.returned': 'Zurück',
    'detail.share': 'Teilen',
    'detail.status': 'Status',
    'detail.wishlist': 'Wunschliste (habe ich noch nicht)',
    'field.ageFrom': 'Alter ab',
    'field.category': 'Kategorie',
    'field.ean': 'Barcode (EAN)',
    'field.format': 'Format',
    'field.isbn': 'ISBN',
    'field.kind': 'Art',
    'field.label': 'Label',
    'field.language': 'Sprache',
    'field.notes': 'Notizen',
    'field.pages': 'Seiten',
    'field.playMinutes': 'Spieldauer (Min.)',
    'field.players': 'Spieler:innen',
    'field.playersMax': 'Spieler:innen bis',
    'field.playersMin': 'Spieler:innen ab',
    'field.publisher': 'Verlag',
    'field.room': 'Raum',
    'field.series': 'Reihe',
    'field.seriesOnly': 'Reihe',
    'field.subtitle': 'Untertitel',
    'field.tags': 'Schlagwörter',
    'field.title': 'Titel',
    'field.volume': 'Band / Nr.',
    'field.year': 'Jahr',
    'form.commaHint': 'mehrere mit Komma trennen',
    'form.coverPhoto': 'Cover fotografieren',
    'form.coverRemove': 'Cover entfernen',
    'form.duplicate': 'Schon vorhanden:',
    'form.edit': 'Bearbeiten',
    'form.fillOnline': 'Online suchen & ausfüllen',
    'form.new': 'Neu erfassen',
    'form.tagsHint': 'z. B. Krimi, Kinder, Geschenk',
    'format.audio': 'Hörbuch',
    'format.ebook': 'E-Book',
    'format.physical': 'Gedruckt',
    'kind.all': 'Alles',
    'kind.book': 'Buch',
    'kind.book.pl': 'Bücher',
    'kind.cd': 'CD',
    'kind.cd.pl': 'CDs',
    'kind.dvd': 'DVD',
    'kind.dvd.pl': 'DVDs',
    'kind.game': 'Spiel',
    'kind.game.pl': 'Spiele',
    'less': 'weniger',
    'lib.empty': 'Noch nichts erfasst. Scanne eine ISBN, fotografiere ein Regal oder trage etwas von Hand ein.',
    'lib.kind': 'Art',
    'lib.minRating': 'Mindestens',
    'lib.more': 'Filter',
    'lib.noMatch': 'Nichts gefunden – Filter lockern?',
    'lib.reset': 'Filter zurücksetzen',
    'lib.scope': 'Auswahl',
    'lib.search': 'Titel, Autor:in, ISBN, Notiz …',
    'lib.showMore': '{n} weitere anzeigen',
    'lib.shown': '{n} Treffer',
    'lib.sort': 'Sortieren nach',
    'lib.status': 'Status',
    'more': 'mehr',
    'nav.add': 'Hinzufügen',
    'nav.library': 'Bibliothek',
    'nav.places': 'Orte',
    'nav.settings': 'Einstellungen',
    'nav.settingsShort': 'Optionen',
    'ok': 'OK',
    'optional': 'optional',
    'places.addRoom': 'Raum hinzufügen',
    'places.digital': 'E-Books & Hörbücher',
    'places.done': 'gelesen / gespielt',
    'places.mergeConfirm': '„{name}“ gibt es schon. Alles aus „{room}“ dorthin verschieben?',
    'places.newRoom': 'Name des Raums:',
    'places.none': 'Ohne Ort',
    'places.remove': 'Entfernen',
    'places.removeRoomConfirm': '„{room}“ entfernen? Die {n} Einträge dort werden „ohne Ort“.',
    'places.rename': 'Umbenennen',
    'places.renameRoom': 'Neuer Name für „{room}“:',
    'places.tip': 'Tippe auf einen Raum, um nur dessen Inhalt zu sehen. Mit ✎ benennst du einen Raum um – gibst du den Namen eines anderen Raums ein, werden beide zusammengelegt. Einzelne Einträge verschiebst du in der Bibliothek mit „Auswählen“.',
    'places.want': 'auf der Leseliste',
    'rating': 'Bewertung',
    'rating.n': '{n} Sterne',
    'save': 'Speichern',
    'scan.add': 'Hinzufügen',
    'scan.addWish': 'Auf Wunschliste',
    'scan.added': '{n} hinzugefügt',
    'scan.camError': 'Kamera nicht verfügbar: {e}',
    'scan.edit': 'Bearbeiten',
    'scan.have': 'Schon im Katalog: „{title}“ ({place})',
    'scan.invalid': 'Das ist keine gültige ISBN / EAN.',
    'scan.looking': 'Suche {code} …',
    'scan.manual': 'ISBN / EAN eintippen',
    'scan.manualAdd': 'Von Hand anlegen',
    'scan.mode': 'Modus',
    'scan.mode.check': 'Habe ich das?',
    'scan.mode.own': 'Ins Regal',
    'scan.mode.wish': 'Wunschliste',
    'scan.next': 'Nächster Scan',
    'scan.notFound': '{code} wurde online nicht gefunden.',
    'scan.notHave': 'Noch nicht im Katalog.',
    'scan.open': 'Öffnen',
    'scan.title': 'Barcode scannen',
    'scan.unsupported': 'Die Kamera ist nicht verfügbar. Gib die Nummer unten ein.',
    'scope.all': 'Alle',
    'scope.check': 'Zu prüfen',
    'scope.lent': 'Verliehen',
    'scope.owned': 'Im Regal',
    'scope.recommend': 'Empfohlen',
    'scope.wish': 'Wunschliste',
    'search.busy': 'Suche …',
    'search.go': 'Suchen',
    'search.none': 'Keine Treffer. Anders schreiben oder nur den Titel versuchen.',
    'search.title': 'Online suchen',
    'sel.all': 'Alle {n}',
    'sel.count': '{n} ausgewählt',
    'sel.edit': 'Bearbeiten',
    'sel.start': 'Auswählen',
    'settings.about': 'Bücher, Spiele, DVDs und CDs katalogisieren',
    'settings.ai': 'Regalfoto-Erkennung (Claude)',
    'settings.aiPrivacy': 'Der Schlüssel bleibt nur auf diesem Gerät und wird nur an api.anthropic.com geschickt – zusammen mit den Fotos, die du erkennen lässt.',
    'settings.aiText': 'Für das Erkennen von Buchrücken auf Fotos wird Claude von Anthropic genutzt. Dafür brauchst du einen eigenen API-Schlüssel von console.anthropic.com (kostenpflichtig, ein Regalfoto kostet je nach Modell etwa 2–10 Cent).',
    'settings.categories': 'Kategorien',
    'settings.categoriesText': 'Jeder Eintrag hat eine Hauptkategorie; alles Weitere über Schlagwörter. Umbenennen auf einen vorhandenen Namen legt beide zusammen.',
    'settings.claudeKey': 'Claude-API-Schlüssel',
    'settings.data': 'Daten & Sicherung',
    'settings.dataText': '{n} Einträge, nur auf diesem Gerät gespeichert. Exportiere regelmäßig eine Sicherung – z. B. in Google Drive. Aus der Web-Version: dort exportieren, hier importieren.',
    'settings.googleHow': 'So bekommst du einen Google-Books-Schlüssel',
    'settings.googleHow1': 'console.cloud.google.com öffnen und mit deinem Google-Konto ein Projekt anlegen (z. B. „mybib“).',
    'settings.googleHow2': 'Unter „APIs & Dienste → Bibliothek“ die „Books API“ suchen und aktivieren.',
    'settings.googleHow3': 'Unter „APIs & Dienste → Anmeldedaten“ „Anmeldedaten erstellen → API-Schlüssel“ wählen.',
    'settings.googleHow4': 'Schlüssel kopieren und oben einfügen. Tipp: den Schlüssel auf die „Books API“ beschränken.',
    'settings.googleKey': 'Google-Books-API-Schlüssel',
    'settings.lang': 'Sprache',
    'settings.lookup': 'Online-Daten',
    'settings.lookupText': 'Cover und Details kommen kostenlos von Google Books, Open Library und MusicBrainz. Google Books hat ein gemeinsames Tageslimit; mit eigenem (kostenlosem) Schlüssel aus der Google Cloud Console klappt es zuverlässiger.',
    'settings.model': 'Modell',
    'settings.model.claude-opus-5-5': 'am genauesten',
    'settings.model.claude-sonnet-5-5': 'günstiger, etwas ungenauer',
    'settings.version': 'Version {v}',
    'share.copied': 'In die Zwischenablage kopiert.',
    'share.recommend': 'Meine Empfehlung 👍',
    'sort.added': 'Zuletzt hinzugefügt',
    'sort.creator': 'Autor:in',
    'sort.place': 'Raum',
    'sort.rating': 'Bewertung',
    'sort.title': 'Titel',
    'sort.year': 'Erscheinungsjahr',
    'status.book.active': 'Lese ich',
    'status.book.done': 'Gelesen',
    'status.book.none': '–',
    'status.book.want': 'Will ich lesen',
    'status.cd.active': 'Höre ich',
    'status.cd.done': 'Gehört',
    'status.cd.none': '–',
    'status.cd.want': 'Will ich hören',
    'status.dvd.active': 'Schaue ich',
    'status.dvd.done': 'Gesehen',
    'status.dvd.none': '–',
    'status.dvd.want': 'Will ich sehen',
    'status.game.active': 'Spielen wir oft',
    'status.game.done': 'Gespielt',
    'status.game.none': '–',
    'status.game.want': 'Will ich spielen',
  },
  'en': {
    'add.cover': 'Photograph cover',
    'add.coverText': 'Photograph the front – the photo becomes the cover, the title is recognised (with API key) or typed in.',
    'add.import': 'Import file',
    'add.importText': 'JSON file from a backup or from a Claude session (shelf photos).',
    'add.manual': 'Type it in',
    'add.manualText': 'For games, DVDs, old or Chinese editions without a barcode.',
    'add.scan': 'Scan barcode',
    'add.scanText': 'ISBN or EAN with the camera – cover and details come from the internet. Also for “do I own this?” in the bookshop.',
    'add.search': 'Search online',
    'add.searchText': 'Search Google Books, Open Library and MusicBrainz by title and author.',
    'add.shelf': 'Recognise shelf photo',
    'add.shelfText': 'Photograph a whole shelf, Claude reads the spines, you check the list.',
    'add.shelfTextNoKey': 'Needs a Claude API key (Options).',
    'add.tip': 'Tip: the room you choose when adding is remembered for the next entry.',
    'ai.addN': 'Add {n}',
    'ai.added': '{n} entries added. Uncertain ones are marked “To check”.',
    'ai.all': 'Select all',
    'ai.camera': 'Camera',
    'ai.conf.low': 'guessed',
    'ai.conf.medium': 'unsure',
    'ai.coverHint': 'The photo is saved as the cover; title and details are recognised and completed online.',
    'ai.coverNoKey': 'The photo is saved as the cover; you type the title (or search for it online).',
    'ai.dup': 'already there',
    'ai.enrich': 'Complete cover & details online (books, CDs)',
    'ai.enriching': 'Looking up details online …',
    'ai.enrichingN': 'Completing online {i} / {n} …',
    'ai.err.auth': 'The API key was rejected. Please check it under Options.',
    'ai.err.network': 'No connection to Claude.',
    'ai.err.other': 'Claude error',
    'ai.err.parse': 'Could not read the answer',
    'ai.err.rate': 'Too many requests – wait a moment and try again.',
    'ai.err.refusal': 'Claude declined this photo.',
    'ai.found': '{n} recognised',
    'ai.gallery': 'Gallery',
    'ai.hintPh': 'Hint (optional), e.g. “Chinese classics”',
    'ai.noKey': 'Shelf photo recognition needs your own Claude API key (under Options). Alternatively send the photos to Claude in a chat and import the file it creates.',
    'ai.none': 'Select none',
    'ai.reading': 'Claude is reading photo {i} of {n} … (takes about 30–90 s)',
    'ai.readingCover': 'Claude is reading the cover …',
    'ai.shelfHint': 'Shoot as straight and close as possible, one shelf section per photo. Several photos from the gallery work too.',
    'ai.take': 'Take over',
    'any': 'All',
    'app.loading': 'Loading …',
    'bulk.badKey': 'Google rejected the API key. Please check it under Options (Books API enabled?).',
    'bulk.count': '{n} books with missing info.',
    'bulk.done': 'Done: {found} completed, {missed} not found.',
    'bulk.field.cover': 'cover',
    'bulk.field.description': 'blurb',
    'bulk.field.isbn': 'ISBN',
    'bulk.field.publisher': 'publisher',
    'bulk.field.year': 'year',
    'bulk.found': 'Completed ({n})',
    'bulk.intro': 'Goes through every book missing a cover, publisher, year, ISBN or blurb and looks it up in Google Books (and Open Library) – by ISBN, otherwise by title and author. Only clear matches are used, and only empty fields are filled; your own entries are never overwritten.',
    'bulk.missed': 'Not found ({n})',
    'bulk.missedHint': 'Tap one and try “Complete online” with a different spelling – or photograph the cover.',
    'bulk.noKey': 'Without your own Google Books key the shared daily limit is often reached quickly. With a key (free, 1,000 lookups per day) it runs reliably.',
    'bulk.nothing': 'All books are complete – or have been looked up already.',
    'bulk.quota': 'Google Books daily limit reached. Continue tomorrow or add your own key – the remaining books stay queued for the next run.',
    'bulk.retry': 'Also retry the {n} looked up before',
    'bulk.short': 'Fetch cover, publisher, year, ISBN and blurb for all books at once from Google Books.',
    'bulk.start': 'Complete {n} books',
    'bulk.stop': 'Stop',
    'bulk.stopped': 'Stopped. The next run continues with the remaining ones.',
    'bulk.title': 'Fill in missing info',
    'bulkEdit.addTag': 'Add tag',
    'bulkEdit.apply': 'Apply to {n}',
    'bulkEdit.checked': 'Remove “to check” mark',
    'bulkEdit.deleteConfirm': 'Really delete {n} entries?',
    'bulkEdit.intro': 'Only what you change here is applied to all selected entries – everything else stays as it is.',
    'bulkEdit.newRoom': 'New room …',
    'bulkEdit.no': 'No',
    'bulkEdit.noRating': 'No rating',
    'bulkEdit.noStatus': 'No status',
    'bulkEdit.owned': 'I own it',
    'bulkEdit.removeTag': 'Remove tag',
    'bulkEdit.title': 'Edit {n} entries',
    'bulkEdit.unchanged': '– unchanged –',
    'bulkEdit.yes': 'Yes',
    'cat.add': 'Add category',
    'cat.mergeConfirm': '“{to}” already exists. Move everything from “{from}” there?',
    'cat.new': 'Name of the new category:',
    'cat.none': '– no category –',
    'cat.own': 'Own',
    'cat.removeConfirm': 'Remove category “{name}”? {n} entries will lose it.',
    'cat.rename': 'New name for “{name}”:',
    'cat.reset': 'Restore default list',
    'cat.resetConfirm': 'Reset the list to the default categories? Categories already used by entries are kept.',
    'close': 'Close',
    'cover.camera': 'Take photo',
    'cover.change': 'Change cover',
    'cover.gallery': 'From gallery',
    'cover.useOnline': 'Remove own photo (show online cover)',
    'creator.book': 'Author',
    'creator.cd': 'Artist',
    'creator.dvd': 'Director',
    'creator.game': 'Designer / publisher',
    'data.exportCsv': 'Export as spreadsheet (CSV)',
    'data.exportCsvShare': 'Share spreadsheet (CSV)',
    'data.exportJson': 'Export backup (JSON)',
    'data.exportJsonShare': 'Share backup (e.g. to Google Drive)',
    'data.import': 'Import backup / file',
    'data.importError': 'Import failed: {e}',
    'data.imported': 'Import: {added} new, {updated} updated, {skipped} skipped (already there).',
    'data.saved': 'Saved.',
    'data.wipe': 'Delete everything',
    'data.wipeConfirm': 'Really delete all {n} entries? Export a backup first!',
    'data.wipeType': 'Type OK to confirm:',
    'detail.checked': 'Looks right',
    'detail.close': 'Close',
    'detail.delete': 'Delete',
    'detail.deleteConfirm': 'Really delete “{title}”?',
    'detail.edit': 'Edit',
    'detail.enrich': 'Complete online',
    'detail.lend': 'Lend …',
    'detail.lendWho': 'To whom?',
    'detail.lentTo': 'Lent to {name} since {date}',
    'detail.loan': 'Lending',
    'detail.loanPast': '{name}: {from} – {to}',
    'detail.needsCheck': 'Recognised automatically – please check title and author.',
    'detail.notesPh': 'What did you like? Who would enjoy it?',
    'detail.place': 'Location',
    'detail.recommend': 'Recommendation',
    'detail.returned': 'Returned',
    'detail.share': 'Share',
    'detail.status': 'Status',
    'detail.wishlist': 'Wishlist (don’t own it yet)',
    'field.ageFrom': 'Age from',
    'field.category': 'Category',
    'field.ean': 'Barcode (EAN)',
    'field.format': 'Format',
    'field.isbn': 'ISBN',
    'field.kind': 'Kind',
    'field.label': 'Label',
    'field.language': 'Language',
    'field.notes': 'Notes',
    'field.pages': 'Pages',
    'field.playMinutes': 'Playing time (min)',
    'field.players': 'Players',
    'field.playersMax': 'Players to',
    'field.playersMin': 'Players from',
    'field.publisher': 'Publisher',
    'field.room': 'Room',
    'field.series': 'Series',
    'field.seriesOnly': 'Series',
    'field.subtitle': 'Subtitle',
    'field.tags': 'Tags',
    'field.title': 'Title',
    'field.volume': 'Volume / no.',
    'field.year': 'Year',
    'form.commaHint': 'separate several with commas',
    'form.coverPhoto': 'Photograph cover',
    'form.coverRemove': 'Remove cover',
    'form.duplicate': 'Already there:',
    'form.edit': 'Edit',
    'form.fillOnline': 'Search online & fill in',
    'form.new': 'New entry',
    'form.tagsHint': 'e.g. crime, kids, gift',
    'format.audio': 'Audiobook',
    'format.ebook': 'E-book',
    'format.physical': 'Print',
    'kind.all': 'Everything',
    'kind.book': 'Book',
    'kind.book.pl': 'Books',
    'kind.cd': 'CD',
    'kind.cd.pl': 'CDs',
    'kind.dvd': 'DVD',
    'kind.dvd.pl': 'DVDs',
    'kind.game': 'Game',
    'kind.game.pl': 'Games',
    'less': 'less',
    'lib.empty': 'Nothing here yet. Scan an ISBN, photograph a shelf or type something in.',
    'lib.kind': 'Kind',
    'lib.minRating': 'At least',
    'lib.more': 'Filter',
    'lib.noMatch': 'Nothing found – loosen the filters?',
    'lib.reset': 'Reset filters',
    'lib.scope': 'Selection',
    'lib.search': 'Title, author, ISBN, note …',
    'lib.showMore': 'Show {n} more',
    'lib.shown': '{n} matches',
    'lib.sort': 'Sort by',
    'lib.status': 'Status',
    'more': 'more',
    'nav.add': 'Add',
    'nav.library': 'Library',
    'nav.places': 'Places',
    'nav.settings': 'Settings',
    'nav.settingsShort': 'Options',
    'ok': 'OK',
    'optional': 'optional',
    'places.addRoom': 'Add room',
    'places.digital': 'e-books & audiobooks',
    'places.done': 'read / played',
    'places.mergeConfirm': '“{name}” already exists. Move everything from “{room}” there?',
    'places.newRoom': 'Room name:',
    'places.none': 'No location',
    'places.remove': 'Remove',
    'places.removeRoomConfirm': 'Remove “{room}”? Its {n} entries will have no location.',
    'places.rename': 'Rename',
    'places.renameRoom': 'New name for “{room}”:',
    'places.tip': 'Tap a room to see only what’s there. Use ✎ to rename a room – entering the name of another room merges both. Move single entries in the library with “Select”.',
    'places.want': 'on the reading list',
    'rating': 'Rating',
    'rating.n': '{n} stars',
    'save': 'Save',
    'scan.add': 'Add',
    'scan.addWish': 'Add to wishlist',
    'scan.added': '{n} added',
    'scan.camError': 'Camera not available: {e}',
    'scan.edit': 'Edit',
    'scan.have': 'Already in the catalogue: “{title}” ({place})',
    'scan.invalid': 'That is not a valid ISBN / EAN.',
    'scan.looking': 'Looking up {code} …',
    'scan.manual': 'Type ISBN / EAN',
    'scan.manualAdd': 'Enter by hand',
    'scan.mode': 'Mode',
    'scan.mode.check': 'Do I own it?',
    'scan.mode.own': 'To shelf',
    'scan.mode.wish': 'Wishlist',
    'scan.next': 'Next scan',
    'scan.notFound': '{code} was not found online.',
    'scan.notHave': 'Not in the catalogue yet.',
    'scan.open': 'Open',
    'scan.title': 'Scan barcode',
    'scan.unsupported': 'The camera is not available. Type the number below.',
    'scope.all': 'All',
    'scope.check': 'To check',
    'scope.lent': 'Lent out',
    'scope.owned': 'On the shelf',
    'scope.recommend': 'Recommended',
    'scope.wish': 'Wishlist',
    'search.busy': 'Searching …',
    'search.go': 'Search',
    'search.none': 'No results. Try another spelling or just the title.',
    'search.title': 'Search online',
    'sel.all': 'All {n}',
    'sel.count': '{n} selected',
    'sel.edit': 'Edit',
    'sel.start': 'Select',
    'settings.about': 'catalogue books, games, DVDs and CDs',
    'settings.ai': 'Shelf photo recognition (Claude)',
    'settings.aiPrivacy': 'The key stays on this device and is only sent to api.anthropic.com – together with the photos you have recognised.',
    'settings.aiText': 'Reading spines on photos uses Claude by Anthropic. You need your own API key from console.anthropic.com (paid; one shelf photo costs roughly 2–10 cents depending on the model).',
    'settings.categories': 'Categories',
    'settings.categoriesText': 'Every entry has one main category; use tags for anything else. Renaming to an existing name merges both.',
    'settings.claudeKey': 'Claude API key',
    'settings.data': 'Data & backup',
    'settings.dataText': '{n} entries, stored only on this device. Export a backup regularly – e.g. to Google Drive. From the web version: export there, import here.',
    'settings.googleHow': 'How to get a Google Books key',
    'settings.googleHow1': 'Open console.cloud.google.com and create a project with your Google account (e.g. “mybib”).',
    'settings.googleHow2': 'Under “APIs & Services → Library” search for “Books API” and enable it.',
    'settings.googleHow3': 'Under “APIs & Services → Credentials” choose “Create credentials → API key”.',
    'settings.googleHow4': 'Copy the key and paste it above. Tip: restrict the key to the “Books API”.',
    'settings.googleKey': 'Google Books API key',
    'settings.lang': 'Language',
    'settings.lookup': 'Online data',
    'settings.lookupText': 'Covers and details come free from Google Books, Open Library and MusicBrainz. Google Books has a shared daily limit; your own (free) key from the Google Cloud Console makes it more reliable.',
    'settings.model': 'Model',
    'settings.model.claude-opus-5-5': 'most accurate',
    'settings.model.claude-sonnet-5-5': 'cheaper, a bit less accurate',
    'settings.version': 'Version {v}',
    'share.copied': 'Copied to the clipboard.',
    'share.recommend': 'I recommend it 👍',
    'sort.added': 'Recently added',
    'sort.creator': 'Author',
    'sort.place': 'Room',
    'sort.rating': 'Rating',
    'sort.title': 'Title',
    'sort.year': 'Year',
    'status.book.active': 'Reading',
    'status.book.done': 'Read',
    'status.book.none': '–',
    'status.book.want': 'Want to read',
    'status.cd.active': 'Listening',
    'status.cd.done': 'Listened',
    'status.cd.none': '–',
    'status.cd.want': 'Want to listen',
    'status.dvd.active': 'Watching',
    'status.dvd.done': 'Watched',
    'status.dvd.none': '–',
    'status.dvd.want': 'Want to watch',
    'status.game.active': 'Play often',
    'status.game.done': 'Played',
    'status.game.none': '–',
    'status.game.want': 'Want to play',
  },
};
